name:                ultimate-tic-tac-toe
version:             0.1.0.0
github:              "githubuser/ultimate-tic-tac-toe"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ultimate-tic-tac-toe#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


executables:
  ultimate-tic-tac-toe-server:
    main-is:                Server.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Server
    dependencies:
    - bytestring
    - utf8-string
    - network >= 2.6.1.0
    - cereal
    - brick
    - containers
    - vty

  ultimate-tic-tac-toe-client:
    main-is:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Main
    dependencies:
    - bytestring
    - utf8-string
    - network >= 2.6.1.0
    - cereal
    - brick
    - containers
    - vty


tests:
  ultimate-tic-tac-toe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
